"""Designer agent — Tamarind BindCraft first, then sequence_design, then fixtures.

Proto/Modal is deliberately not used: Tamarind hosts the same models (RFdiffusion3,
ProteinMPNN) plus BindCraft, against an API key that already works, so there is no
second GPU stack to keep deployed.
"""

from __future__ import annotations

import json
import shutil
import time
from pathlib import Path

from backend.config import DATA_DIR, FIXTURES_DIR
from backend.contracts.validate import validate_designs
from backend.tools.sequence_design import designs_to_fasta


AGENT_NAME = "designer"
AGENT_DISPLAY = "Sequence design (BindCraft)"

BINDCRAFT_DIR = DATA_DIR / "bindcraft_designs"


def _engine_from_doc(doc: dict | None, default: str) -> str:
    meta = (doc or {}).get("meta") or {}
    return str(meta.get("design_engine") or default)


def _load_bindcraft_designs() -> dict | None:
    """Load a completed BindCraft campaign from disk, if one exists."""
    path = BINDCRAFT_DIR / "designs.json"
    if not path.is_file():
        return None
    try:
        doc = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None
    return doc if doc.get("designs") else None


def run_designer(state: dict, progress_cb=None) -> dict:
    start = time.perf_counter()
    run_dir = Path(state["run_dir"])
    mode = state.get("mode", "fixture")
    provenance_nodes = dict(state.get("provenance_nodes") or {})
    tool_calls: list[dict] = []
    steps: list[dict] = []
    designs_doc: dict | None = None
    node_source = "fixture"
    engine = "none"

    if progress_cb:
        progress_cb(AGENT_NAME, "running", step="Designing binder sequences...")

    if mode == "replay":
        path = run_dir / "designs.json"
        designs_doc = json.loads(path.read_text())
        node_source = "cached"
        engine = _engine_from_doc(designs_doc, "cached")
        steps.append({"action": "Load cached designs", "detail": str(path)})
        fasta_path = run_dir / "designs.fasta"
        if not fasta_path.exists():
            fasta_path.write_text(
                designs_to_fasta(designs_doc.get("designs") or [])
            )
    else:
        if mode == "live":
            # BindCraft runs for hours on Tamarind's GPUs, so it cannot be called
            # inline per run. A completed campaign is picked up from disk here.
            bindcraft_doc = _load_bindcraft_designs()
            if bindcraft_doc:
                designs_doc = bindcraft_doc
                # Read the engine off the campaign rather than assuming BindCraft:
                # the same drop path is used by esmfold2-binder-design, whose output
                # has NOT passed BindCraft's acceptance filters. Claiming otherwise
                # would be the exact mislabelling the provenance banner exists to stop.
                engine = _engine_from_doc(bindcraft_doc, "bindcraft")
                node_source = "live"
                filtered = engine == "bindcraft"
                tool_calls.append(
                    {
                        "tool": f"tamarind.{engine}",
                        "detail": (
                            "RFdiffusion + ProteinMPNN + AF2 with acceptance filters"
                            if filtered
                            else "single-shot generative binder design, no acceptance filters"
                        ),
                        "job_name": (bindcraft_doc.get("meta") or {}).get("job_name"),
                    }
                )
                steps.append(
                    {
                        "action": f"Structure-based designs ({engine})",
                        "detail": (
                            f"{len(bindcraft_doc['designs'])} designs that passed "
                            "BindCraft acceptance filters"
                            if filtered
                            else f"{len(bindcraft_doc['designs'])} designs — generated by "
                            f"{engine}, NOT filter-passed; judged only by our critic"
                        ),
                    }
                )

        if designs_doc is None and mode == "live":
            try:
                from backend.tools.sequence_design import generate_designs

                tool_calls.append(
                    {
                        "tool": "sequence_design.local",
                        "detail": "Local interim generator — used only until a BindCraft campaign lands",
                    }
                )
                result = generate_designs(state.get("scientific_spec") or {})
                if result and result.get("designs"):
                    designs_doc = result
                    engine = "sequence_design"
                    node_source = "live"
                    steps.append(
                        {
                            "action": "Local sequence_design (no BindCraft campaign on disk)",
                            "detail": (
                                f"{len(result['designs'])} sequences; engine=sequence_design; "
                                "heuristic — not a structure-based design"
                            ),
                        }
                    )
            except Exception as e:  # noqa: BLE001
                steps.append({"action": "Design unavailable", "detail": str(e)})
                engine = "unavailable"

        if designs_doc is None:
            src_json = FIXTURES_DIR / "designs.example.json"
            src_fa = FIXTURES_DIR / "designs.example.fasta"
            shutil.copy2(src_json, run_dir / "designs.json")
            shutil.copy2(src_fa, run_dir / "designs.fasta")
            designs_doc = json.loads((run_dir / "designs.json").read_text())
            for d in designs_doc.get("designs") or []:
                d["provenance"] = "fixture"
            designs_doc.setdefault("meta", {})["design_engine"] = "fixture"
            (run_dir / "designs.json").write_text(json.dumps(designs_doc, indent=2))
            node_source = "fixture"
            engine = "fixture"
            steps.append({"action": "Load fixture designs", "detail": str(src_json)})

    validate_designs(designs_doc)
    designs_doc.setdefault("meta", {})["design_engine"] = engine
    (run_dir / "designs.json").write_text(json.dumps(designs_doc, indent=2))
    if not (run_dir / "designs.fasta").exists():
        (run_dir / "designs.fasta").write_text(
            designs_to_fasta(designs_doc.get("designs") or [])
        )

    provenance_nodes[AGENT_NAME] = node_source
    elapsed = time.perf_counter() - start
    n = len(designs_doc.get("designs") or [])
    if engine == "bindcraft":
        honest = f"engine={engine} (Tamarind BindCraft — structure-based, filter-passed)"
    elif engine in {"esmfold2-binder-design", "rfdiffusion3", "boltzdesign", "boltzgen"}:
        honest = f"engine={engine} (Tamarind — structure-based, NOT filter-passed)"
    else:
        honest = f"engine={engine} (heuristic — not a structure-based design)"
    trace = {
        "agent": AGENT_NAME,
        "agent_name": AGENT_DISPLAY,
        "duration_seconds": round(elapsed, 2),
        "model": "bindcraft" if engine == "bindcraft" else None,
        "input_summary": f"mode={mode}; design_engine={engine}",
        "output_summary": f"{n} designs; {honest}",
        "steps": steps,
        "tool_calls": tool_calls,
    }
    traces = list(state.get("agent_traces") or [])
    traces.append(trace)
    return {
        "designs": designs_doc,
        "provenance_nodes": provenance_nodes,
        "agent_traces": traces,
    }
